//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Flooring.rc
//
#define IDS_NATURETITLE                 1
#define IDS_ACTIONTITLE                 2
#define IDS_CAUSETITLE                  3
#define ID_REJECTCHANGES                3
#define ID_INDICATOR_USERNAME           4
#define IDD_ABOUTBOX                    100
#define IDD_FLOORING_FORM               101
#define IDP_FAILED_OPEN_DATABASE        103
#define IDD_CUSTSATPROPERTYPAGE         106
#define IDD_ORDERPROPPAGE               107
#define IDR_HTML_DLGSELECTDEPARTMENT    108
#define IDC_ANIMATE                     109
#define IDR_WORKSPACEBAR                111
#define IDR_FINDCUSTOMERS_TMPL          112
#define IDD_VIEWACTIVITYLIST            113
#define IDD_REPORTDIALOGWF              120
#define IDD_DATABASECONFIGWF            121
#define IDD_DLGUNITTESTRESULTS          122
#define IDR_MAINFRAME                   128
#define IDR_CUSTOMTYPE                  129
#define IDD_STORE                       130
#define IDR_REPORT                      131
#define IDD_SUBCONTRACTOR               132
#define IDD_PO                          133
#define IDB_DEPOT                       135
#define IDB_EXPOBITMAP                  136
#define IDD_SCHEDULE                    137
#define IDD_INVOICING                   139
#define IDD_CHECK                       140
#define IDC_CURSOR1                     141
#define IDR_CUSTOMER                    142
#define IDD_FIND                        143
#define IDD_CHARGEBACKS                 144
#define IDD_CHARGEBACK                  144
#define IDD_DATE_PICKER                 145
#define IDD_IND_CALLS                   147
#define IDD_MATERIAL_STATUS             148
#define IDD_ACTION_REPORT               149
#define IDC_CURSOR2                     150
#define IDD_CALLED_LIST                 152
#define IDR_PO                          156
#define IDD_STORE_SELECTION             157
#define IDD_REPORT_CONFIG               167
#define ID_REPORTS_PULLLIST             168
#define ID_REPORTS_WEEKLYTOTALS         169
#define IDD_REPORTDLG                   171
#define ID_REPORTS_CHARGEBACKSBYDATE    173
#define ID_REPORTS_COMPLETEDJOBSNOTPAID 174
#define ID_REPORTS_WORKSUMMARYBYWEEK    175
#define IDD_SELECT_MAIL_RECIPIENTS      176
#define IDD_PAYROLL_MARKET_DIVISION_DIALOG 177
#define IDD_REPORT_LIST                 179
#define IDB_UNDERLINEBITMAP             180
#define IDB_BOLDBITMAP                  181
#define IDB_ITALICBITMAP                182
#define IDD_ACTION_REPORT_PROPPAGE      185
#define IDB_TTF_BMP                     187
#define IDD_DELETE_PO_DIALOG            188
#define IDD_TRANSFERPO_DIALOG           189
#define IDD_CHANGEPO_DIALOG             190
#define IDD_CHECK_LIST                  191
#define IDD_CHECK_NEW                   192
#define IDD_CHARGEBACK_LIST             193
#define IDD_SUBCONTRACTORS_PICKLIST     194
#define IDD_STORES_PICKLIST             195
#define IDD_POENTRY                     196
#define IDD_MESSAGES_DIALOG             198
#define IDD_SELECT_VENDOR_DIALOG        199
#define IDD_SELECT_CUSTOMER             200
#define IDD_MERGE_CUSTOMERS             202
#define IDD_PAYROLL_MESSAGES            203
#define IDD_PAYROLL_MESSAGE_EDIT        204
#define IDD_DISCREPANCIES               205
#define IDD_STORECUSTDISCREPANCY        206
#define IDD_BL_PROP_PAGE                207
#define IDD_OL_PROP_PAGE                208
#define IDD_CL_PROP_PAGE                209
#define IDD_SO_PROP_PAGE                210
#define IDD_REG_PROP_PAGE               211
#define IDD_SPLIT_LINEITEM_DIALOG       212
#define IDD_STORE_SELECTION1            214
#define IDD_MERCH_SELECTION             214
#define IDD_DEPT_SELECTION              215
#define IDD_SELECT_PO                   216
#define IDD_SPN_DOWNLOAD                217
#define IDD_WEBSERVICE_DIALOG           217
#define IDD_NOTES_PROP_PAGE             219
#define IDD_USER_ALERTS                 220
#define IDD_DIALOG_SUBCONTRACTOR_INSURANCE 221
#define IDD_INSURANCE_QUESTION          222
#define IDD_TROUBLEREPORT_2             223
#define IDD_TROUBLEREPORT_1             224
#define IDD_TROUBLEREPORT_3             225
#define IDD_TROUBLEREPORT_4             226
#define IDD_PASSWORD                    227
#define IDD_USERS_DIALOG                228
#define IDD_PONOTE_ENTRY                229
#define IDD_PONOTES_LIST                230
#define IDD_SCHEDULE_REASONCODE         231
#define IDD_ACTIVE_POS                  232
#define IDD_ACTIVITY_LIST               233
#define IDB_LARGE                       238
#define IDB_SMALL                       240
#define IDD_FINDCUSTOMER                241
#define IDD_EMPTY_DIALOG                242
#define IDD_ATTACHED_DOCS_LIST          243
#define IDD_SENDNOTE                    244
#define IDC_FIRST_NAME                  1001
#define IDC_LAST_NAME                   1002
#define IDC_ADDRESS                     1003
#define IDC_CITY                        1004
#define IDC_STATE                       1005
#define IDC_ZIP                         1006
#define IDC_HOME_PHONE                  1007
#define IDC_WORK                        1008
#define IDC_HOME                        1009
#define IDC_MOBILE_PHONE                1009
#define IDC_EMAIL_ADDRESS               1010
#define IDC_CUSTOMER_FIND               1011
#define IDC_CUSTOMER_EDIT               1012
#define IDC_CUSTOMER_NEW                1013
#define IDC_STATIC_ADDRESS              1015
#define IDC_STATIC_CITY                 1016
#define IDC_STATIC_STATE                1017
#define IDC_STATIC_ZIP                  1018
#define IDC_STATIC_WORK                 1019
#define IDC_STATIC_HOME                 1020
#define IDC_CUSTOMER_PICKLIST           1021
#define IDC_STATIC_PHONEFIELD3          1021
#define IDC_PO_PICKLIST                 1022
#define IDC_PHONE_NUMBER                1023
#define IDC_STORE_PHONE_NUMBER          1023
#define IDC_STATIC_MOBILE               1023
#define IDC_FAX_NUMBER                  1024
#define IDC_STATIC_EMAIL                1024
#define IDC_STORE_TYPE                  1025
#define IDC_STORES_STORETYPE            1025
#define IDC_STORE_NUMBER                1026
#define IDC_STORES_STORENUMBER          1026
#define IDC_CONTACT_FIRST_NAME          1027
#define IDC_STORES_DEPTHEAD_FIRST_NAME  1027
#define IDC_CONTACT_LAST_NAME           1028
#define IDC_STORES_DEPTHEAD_LAST_NAME   1028
#define IDC_CONTACT_PHONE_NUMBER        1029
#define IDC_STORES_EXPEDITOR_PHONE_NUMBER 1029
#define IDC_NICK_NAME                   1030
#define IDC_STORE_MARKET                1030
#define IDC_STORES_MARKET               1030
#define IDC_ALT_FAX_NUMBER              1031
#define IDC_STORES_EXPEDITOR_FIRST_NAME 1032
#define IDC_NOTES                       1033
#define IDC_STORE_NICKNAME              1033
#define IDC_SPEED_DIAL                  1034
#define IDC_STORES_EXPEDITOR_LAST_NAME  1034
#define IDC_STORES_INSTSALESMGR_PHONE_NUMBER 1035
#define IDC_STORES_INSTSALESMGR_FIRST_NAME 1036
#define IDC_STORES_INSTSALESMGR_LAST_NAME 1037
#define IDC_CELL_NUMBER                 1038
#define IDC_PAGER_NUMBER                1039
#define IDC_CRIMINAL_CHECK              1040
#define IDC_SUBCONTRACTOR_BACKGND_RPT_REQ 1040
#define IDC_DATE_CRIMINAL_CHECK         1041
#define IDC_SUBCONTRACTOR_BACKGROUNDCHK_DATE_APPROVED 1041
#define IDC_DATE_INSURANCE              1042
#define IDC_DATE_WORKMANSCOMP_INSURANCE 1042
#define IDC_DATE_LIABILITY_INSURANCE    1043
#define IDC_SSN                         1044
#define IDC_ZIP_CODE                    1046
#define IDC_WORKMANSCOMP_INSURANCE_OK   1047
#define IDC_CUSTOMER_DATA               1048
#define IDC_INSURANCE2                  1048
#define IDC_LIABILITY_INSURANCE_OK      1048
#define IDC_PO_NUMBER                   1049
#define IDC_MATERIALS                   1050
#define IDC_MERCH_PROPSHEET             1050
#define IDC_OPTIONS                     1051
#define IDC_NOTES_PROPSHEET             1051
#define IDC_ORDER_DATE                  1052
#define IDC_ORDER_NO                    1053
#define IDC_PAID                        1055
#define IDC_SCHEDULED                   1056
#define IDC_ORIGINAL_PO                 1056
#define IDC_BILL_AMOUNT                 1057
#define IDC_CUSTOM                      1064
#define IDC_TYPE                        1065
#define IDC_PRICE                       1066
#define IDC_PRICE2                      1067
#define IDC_XMLPRICE                    1067
#define IDC_DEPOT                       1068
#define IDC_DIRECTIONS                  1069
#define IDC_DIRECTIONS_LABLE            1070
#define IDC_NO_MIN                      1071
#define IDC_TRIP_CHARGE                 1072
#define IDC_AM                          1073
#define IDC_PM                          1074
#define IDC_CHECK_DATE                  1075
#define IDC_INVOICEDATE                 1077
#define IDC_INVOICED                    1078
#define IDC_INVOICE_GRID                1079
#define IDC_CHECK_NUMBER                1083
#define IDC_CHECK                       1084
#define IDC_CHECK_AMOUNT                1084
#define IDC_CHECK_GRID                  1085
#define IDC_NUMBER                      1086
#define IDC_CHECK_DIFF                  1086
#define IDC_CANCELLED                   1087
#define IDC_YARDAGE                     1087
#define IDC_INV_PAID                    1088
#define IDC_CHARGEBACK_AMOUNT           1089
#define IDC_CHARGEBACK_CHECK_AMOUNT     1090
#define IDC_WARRENTY                    1091
#define IDC_INSTALLER_AMOUNT            1091
#define IDC_WAR_COMP                    1092
#define IDC_CHARGEBACK_CUSTNAME         1092
#define IDC_CHARGEBACK_SUBCONTRACTOR    1094
#define IDC_COMMENTS                    1095
#define IDC_MONTHCALENDAR1              1096
#define IDC_SEVEN_DAY                   1097
#define IDC_COMMENTS_ADD                1097
#define IDC_CHECK_LIST                  1098
#define IDC_DRAWING_NUMBER              1101
#define IDC_DRAWING_TIME                1102
#define IDC_DRAWING_UPDATE              1103
#define IDC_ACTIVE                      1104
#define IDC_DRAWING_VIEW                1104
#define IDC_ACTIVE2                     1105
#define IDC_HELPER                      1105
#define IDC_DONE                        1108
#define IDC_CALLED_LIST                 1111
#define IDC_LEFT_MESSAGE                1113
#define IDC_NO_ANSWER                   1114
#define IDC_MR                          1115
#define IDC_MS                          1116
#define IDC_OTHER                       1117
#define IDC_OTHER_NAME                  1118
#define IDC_CUST_TO_CALL                1119
#define IDC_BOTH                        1122
#define IDC_CALL_DATE                   1123
#define IDC_DATE_SCHEDULE               1125
#define IDC_CUSTOMER_CALLED             1126
#define IDC_DATE_ENDSCHEDULE            1126
#define IDC_UNSCHEDULED                 1127
#define IDC_STORE_CALLED                1129
#define IDC_CALLED_STORE                1130
#define IDC_GRID                        1131
#define IDC_STORE_FAXED                 1131
#define IDC_FAXED_STORE                 1132
#define IDC_INVOICE                     1135
#define IDC_STYLE                       1137
#define IDC_COLOR                       1138
#define IDC_DRAWINGS                    1139
#define IDC_LABOR_PO                    1140
#define IDC_PADDING_PO                  1141
#define IDC_SCHEDULED_TEXT              1142
#define IDC_BILLED_TEXT                 1143
#define IDC_RETAINAGE                   1145
#define IDC_RETAINAGE_PCT               1145
#define IDC_STORE_SELECTION             1146
#define IDC_WORKCOMP_RATE               1146
#define IDC_WORKCOMP_RATE_PCT           1146
#define IDC_INSURANCE_RATE_PCT          1146
#define IDC_MILL_ERROR                  1147
#define IDC_RETAINAGE_ACCOUNT_BAL       1147
#define IDC_STORE_ERROR                 1148
#define IDC_INSTALLER_ERROR             1149
#define IDC_MEASURE_ERROR               1150
#define IDC_INFO                        1151
#define IDC_REPORT_DATE                 1152
#define IDC_ABOUT_TITLE                 1154
#define IDC_ABOUT_COPYRIGHT             1155
#define IDC_ABOUT_VERSION               1156
#define IDC_REPORTCONFIG_TITLE          1158
#define IDC_REPORTCONFIG_DIVLIST        1159
#define IDC_REPORTCONFIG_MARKETLIST     1160
#define IDC_REPORTCONFIG_ALLMARKETS     1161
#define IDC_REPORTCONFIG_SELECTEDMARKETS 1162
#define IDC_REPORTCONFIG_ALLDIVS        1163
#define IDC_REPORTCONFIG_SELECTEDDIVS   1164
#define IDC_REPORTCONFIG_DTP_START      1165
#define IDC_REPORTCONFIG_STARTDATE      1166
#define IDC_STATIC_ADDNOTES             1167
#define IDC_REPORTCONFIG_DTP_END        1167
#define IDC_BTN_ADD                     1168
#define IDC_REPORTCONFIG_ENDDATE        1168
#define IDC_BTN_EDIT                    1169
#define IDC_STATUS                      1169
#define IDC_REPORTCONFIG_ALLMARKETSANDDIVISIONS 1169
#define IDC_BTN_DELETE                  1170
#define IDC_REPORTCONFIG_SELECTEDMARKETSANDDIVISIONS 1170
#define IDC_CRVIEWER2                   1171
#define IDC_MATERIALSTATUS_CUSTNAME     1173
#define IDC_MATERIALSTATUS_PO           1174
#define IDC_MATERIALSTATUS_RESET        1175
#define IDC_SUBCONTRACTORS_ADD          1175
#define IDC_CHARGEBACK_ADD              1175
#define IDC_ACTION_REPORT_BOLD_BUTTON   1175
#define IDC_SUBCONTRACTORS_EDIT         1176
#define IDC_CHARGEBACK_EDIT             1176
#define IDC_ACTION_REPORT_ITALIC_BUTTON 1176
#define IDC_SUBCONTRACTORS_DELETE       1177
#define IDC_CHARGEBACK_DELETE           1177
#define IDC_ACTION_REPORT_UNDERLINE_BUTTON 1177
#define IDC_CHARGEBACK_NUMBER           1181
#define IDC_CHARGEBACK_CHECK_NUMBER     1182
#define IDC_CHARGEBACK_CHECK_DATE       1183
#define IDC_CHARGEBACK_COMMENTS         1184
#define IDC_RICHEDITNATURECONCERN       1187
#define IDC_REPORT_LIST_HIDDEN_RICH_EDIT 1187
#define IDC_CHARGEBACK_CUSTOMERPICK_COMBO 1188
#define IDC_RICHEDITACTIONREQUIRED      1188
#define IDC_RICHEDITCAUSE               1189
#define IDC_CHARGEBACK_DIVISION         1191
#define IDC_CHARGEBACK_MARKET           1192
#define IDC_CALLS_SAVEANDEMAIL_BUTTON   1196
#define IDC_MAIL_EMPLOYEES_LIST         1197
#define IDC_MAIL_RECIPIENTS_LIST        1198
#define IDC_MAIL_ADD_BUTTON             1199
#define IDC_MAIL_REMOVE_BUTTON          1200
#define IDC_INSTALLER_QUICKPICK_COMBO   1200
#define IDC_TRANSACTION_MARKET_COMBO    1200
#define IDC_MAIL_REMOVE_ALL_BUTTON      1201
#define IDC_MAIL_ADD_ALL_BUTTON         1202
#define IDC_TRANSACTION_TYPE_COMBO      1202
#define IDC_TRANSACTION_DIVISION_COMBO  1203
#define IDC_TRANSACTION_DETAILS_STATIC  1204
#define IDC_REPORT_LIST                 1205
#define IDC_BUTTON1                     1208
#define IDC_ACTION_REPORT_CHECKSPELLING 1208
#define IDC_TRANSFERPO_FINDBUTTON       1208
#define IDC_MESSAGES_PRINT              1208
#define IDC_FIND_BUTTON                 1208
#define IDC_VIEW_WORKORDER              1208
#define IDC_SUB_PICTURE_SELECT          1208
#define IDC_CANCEL_PAYROLL_BUTTON       1208
#define IDC_BUTTON_RESET                1208
#define IDC_BTNRESET                    1208
#define IDC_BTN_ATTACHDOCUMENT          1208
#define IDC_ACTION_REPORT_VIEWPRINTREPORT_BUTTON 1209
#define IDC_STATIC_ACTION_REPORT_TODAY  1210
#define IDC_NATURE_EXISTING             1211
#define IDC_NATURE_ADDITIONAL           1212
#define IDC_CAUSE_EXISTING              1213
#define IDC_CAUSE_ADDITIONAL            1214
#define IDC_ACTION_EXISTING             1215
#define IDC_PROPSHEET                   1215
#define IDC_ACTION_ADDITIONAL           1216
#define IDC_ACTIONREPORT_FONTCOMBO      1219
#define IDC_ACTIONREPORT_FONTSIZE_COMBO 1220
#define IDC_REPORTCONFIG_MARKETDIVISIONLISTBOX 1221
#define IDC_RETAINAGE_TXT_1             1222
#define IDC_RETAINAGE_TXT_2             1223
#define IDC_ACTION_REPORT_EXISTING_NOTES 1223
#define IDC_ACTION_REPORT_ADDITIONAL_NOTES 1224
#define IDC_DELETE_PO_DIALOG_YES        1225
#define IDC_DELETE_PO_DIALOG_TEXT       1226
#define IDC_TRANSFERPO_DIALOG_COMBO     1227
#define IDC_TRANSFERPO_DIALOG_LASTNAME  1228
#define IDC_TRANSFERPO_DIALOG_CUSTNAME  1228
#define IDC_TRANSFERPO_DIALOG_CUSTID    1229
#define IDC_TRANSFER_DIALOG_MESSAGE     1230
#define IDC_CHANGEPO_DIALOG_POEDIT      1231
#define IDC_CHANGEPO_DIALOG_MESSAGE     1232
#define IDC_TRANSFERPO_CUSTLNAME        1234
#define IDC_TRANSFERPO_CUSTFNAME        1235
#define IDC_TRANSFERPO_CUST_PICK_LIST   1236
#define IDC_CHECK1                      1238
#define IDC_STORE_RECEIVE_FAX_STATUS    1238
#define IDC_APPROVED                    1238
#define IDC_SUBCONTRACTORSPICKLIST_SHOWACTIVEONLY 1238
#define IDC_SUBCONTRACTOR_BACKGND_CHECK_PASSED 1238
#define IDC_STORES_SHOWACTIVE           1238
#define IDC_STORES_RECEIVE_FAX_STATUS   1238
#define IDC_CHECK_ONLY_MY_POS           1238
#define IDC_INCLUDEINSTATUSREPORTALLSTORES 1238
#define IDC_CHARGEBACK_LIST             1239
#define IDC_EDIT2                       1241
#define IDC_SUBCONTRACTOR_BADGE_STATUS  1241
#define IDC_STORENEWEDIT                1241
#define IDC_EDIT_BALANCE                1241
#define IDC_EDIT_NOTES                  1241
#define IDC_SUB_INSURANCE_PCT           1241
#define IDC_EDIT_ACTIVITY_CLOSED_BY     1241
#define IDC_EDIT_HOMEPHONE              1241
#define IDC_LIST1                       1242
#define IDC_STORECURRENTEDIT            1242
#define IDC_EDIT_MOBILEPHONE            1242
#define IDC_EDIT3                       1243
#define IDC_APPROVAL_NUMBER             1243
#define IDC_EDIT_TROUBLE_REPORT_PONUMBER 1243
#define IDC_EDIT_WORKPHONE              1243
#define IDC_SUBCONTRACTOR_ASSIGNEDTO    1244
#define IDC_EDIT_EMAILADDRESS           1244
#define IDC_WORKCOMP_RATE_DOLLAR        1245
#define IDC_INSURANCE_RATE_DOLLAR       1245
#define IDC_SUBS_GRID                   1246
#define IDC_SUBCONTRACTOR_ASSIGNEDTO2   1246
#define IDC_SUBCONTRACTOR_BRANCHOFFICE  1246
#define IDC_RETAINAGE_GROUP             1247
#define IDC_INSURANCE_PCT_TXT           1248
#define IDC_INSURANCE_DOLLAR_TXT        1249
#define IDC_INSURANCE_TXT_1             1250
#define IDC_INSURANCE_GROUP             1251
#define IDC_STORES_GRID                 1252
#define IDC_STORES_ACTIVE_CHECK         1253
#define IDC_STORES_NOTES                1254
#define IDC_STORES_ADDRESS              1255
#define IDC_STORES_LABEL1               1256
#define IDC_STORES_LABEL2               1257
#define IDC_STORES_LABEL3               1258
#define IDC_STORES_LABEL4               1259
#define IDC_RETAINAGE_TXT_3             1260
#define IDC_SUBCONTRACTOR_DIVISIONS     1261
#define IDC_POENTRY_PONUMBEREDIT        1262
#define IDC_POENTRY_POTYPECOMBO         1263
#define IDC_POENTRY_ORIGPOCOMBO         1264
#define IDC_PO_TYPE                     1265
#define IDC_POENTRY_STORENUMBER         1266
#define IDC_DEPOT_BMP                   1266
#define IDC_MESSAGES_LISTTITLE          1267
#define IDC_MESSAGES_LIST               1268
#define IDC_EXPIRES_TEXT                1269
#define IDC_CHECK_VENDOR                1270
#define IDC_EXPIRES_TEXT2               1270
#define IDC_COMBO1                      1271
#define IDC_SELECT_VENDOR_COMBO         1271
#define IDC_FILTER_COMBO                1271
#define IDC_COMBO_CUSTOMER              1271
#define IDC_PO_COMBO                    1271
#define IDC_STORECOMBO                  1271
#define IDC_EXPIRES_TEXT3               1271
#define IDC_STATUS_COMBO                1272
#define IDC_STATIC_PO_NUMBER            1273
#define IDC_MASKEDNUMBER                1274
#define IDC_RADIO_CUST1                 1275
#define IDC_RADIO_CUST2                 1276
#define IDC_STATIC_CUST1                1277
#define IDC_STATIC_CUST2                1278
#define IDC_PAYROLL_GRID                1279
#define IDC_MESSAGE_TEXT                1280
#define IDC_DTP_START                   1281
#define IDC_DTPEND                      1282
#define IDC_DISCREPANCIESGRID           1283
#define IDC_STORENEWADDRESS             1284
#define IDC_STORECURRENTADDRESS         1285
#define IDC_STATIC_CURRENT              1288
#define IDC_STATIC_NEW                  1289
#define IDC_DISC_EXTRAINFO              1290
#define IDC_SO_GRID_AREA                1293
#define IDC_BL_GRID_AREA                1295
#define IDC_CL_GRID_AREA                1296
#define IDC_OL_GRID_AREA                1297
#define IDC_REG_GRID_AREA               1298
#define IDC_LABOR_GRID                  1299
#define IDC_EDIT_NEWAMOUNT              1300
#define IDC_SPLIT_TEXT                  1301
#define IDC_MATERIAL_STATIC             1302
#define IDC_ORDERNUM_STATIC             1303
#define IDC_TRIPCHARGE_STATIC           1304
#define IDC_POAMOUNT_STATIC             1305
#define IDC_AMOUNTTOBILL_STATIC         1306
#define IDC_DRAWING_STATIC              1307
#define IDC_XMLPOAMOUNT_STATIC          1308
#define IDC_SUMMARY_EDIT                1309
#define IDC_CUSTNAME_STATIC             1310
#define IDC_PO_STATIC                   1311
#define IDC_STATUS_STATIC               1312
#define IDC_CONTACT_GRID_PLACEHOLDER    1313
#define IDC_MERCH_SELECTION             1315
#define IDC_DEPT_SELECTION              1316
#define IDC_BUTTON2                     1317
#define IDC_REFRESH_PRICES              1317
#define IDC_ANIMATION                   1318
#define IDC_ST_STORE                    1319
#define IDC_CALLS                       1320
#define IDC_EDIT1                       1321
#define IDC_EDIT_NUMALERTS              1321
#define IDC_SUB_INSURANCE_DOLLAR        1321
#define IDC_EDIT_TROUBLE_REPORT_DESCRIPTION 1321
#define IDC_EDIT_PASSWORD               1321
#define IDC_PONOTE_OTHEREDIT            1321
#define IDC_EDIT_ACTIVITY_ADD_INFO      1321
#define IDC_MATERIAL_DESCRIPTION        1322
#define IDC_USER_DISCREPANCIES_GRID     1323
#define IDC_BTN_ALERTS                  1324
#define IDC_REVIEWED_STATUS             1325
#define IDC_                            1326
#define IDC_CHECK_AUTOUPDATE            1326
#define IDC_SUBCONTRACTOR_PIC           1327
#define IDC_SUB_INSURANCE_SUBNAME       1328
#define IDC_INSURANCE_QUESTION_MESSAGE  1329
#define IDC_RADIO_YES                   1330
#define IDC_RADIO_NO                    1331
#define IDC_COMBO_STORENUMBER           1333
#define IDC_EDIT_TROUBLE_REPORT_SUMMARY 1334
#define IDC_USER_COMBO                  1335
#define IDC_PONOTE_COMBO_NOTETYPE       1337
#define IDC_PONOTE_COMBO_SPOKEWITH      1338
#define IDC_PONOTE_SPOKEWITH_GROUP      1339
#define IDC_PONOTE_NOTETYPE_GROUP       1340
#define IDC_PONOTE_SAVEANDEMAIL_BUTTON  1341
#define IDC_PONOTE_NOTES                1342
#define IDC_PONOTES_NOTESADD            1343
#define IDC_PONOTES_LIST                1345
#define IDC_STATIC_PHONEGROUP           1346
#define IDC_STATIC_PHONEFIELD1          1347
#define IDC_STATIC_PHONEFIELD2          1348
#define IDC_DIAGRAMNAME_STATIC          1349
#define IDC_COMBO_REASONS               1350
#define IDC_SCHEDULE_GROUPBOX           1351
#define IDC_STATIC_SCHEDULETEXT         1352
#define IDC_SO_MERCH_GRID_AREA          1355
#define IDC_STATIC_CURRENT_SCHEDULE_DATE 1356
#define IDC_ACTIVE_POS_GRID             1357
#define IDC_EDIT_NUMPOS                 1358
#define IDC_ACTIVEPOS_SHOWONLYACTIVEPOS 1359
#define IDC_ACTIVEPOS_SHOWALLACTIVEPOS  1359
#define IDC_ACTIVEPOS_SHOWPOSWITHALERTS 1360
#define IDC_ACTIVEPOS_DTP_START         1361
#define IDC_ACTIVEPOS_DTP_END           1362
#define IDC_ACTIVEPOS_INCLUDECANCELLEDPOS 1363
#define IDC_ACTIVITY_LIST_GRID          1364
#define IDC_CHECK_ONLY_MY_ACTIVITIES    1365
#define IDC_ACTIVITIES_SHOWALLACTIVITIES 1366
#define IDC_ACTIVITIES_DTP_START        1368
#define IDC_ACTIVITIES_DTP_END          1369
#define IDC_ACTIVITIES_SHOW_ONLY_OPEN_ACTIVITIES 1370
#define IDC_LEGENDGROUP                 1372
#define IDC_CUSTOMERINFO_GROUP          1373
#define IDC_DIRECTIONS_GROUP            1374
#define IDC_STATIC_POJOBS               1375
#define IDC_TEXT_CUSTOMERNAME           1376
#define IDC_TEXT_CUSTOMER_ADDRESS       1377
#define IDC_STATIC_STARTDATE            1378
#define IDC_STATIC_ENDDATE              1379
#define IDC_STATIC_NOTETEXT             1380
#define IDC_CHECKNOTETOSASM             1381
#define IDC_CHECKNOTETOSASM2            1382
#define IDC_CHECKNOTETOEXPEMAIL         1382
#define IDC_CUSTOMERNAME                1383
#define IDC_SITEADDRESS                 1384
#define IDC_UNIT_TEST_RESULTS_LIST      1385
#define ID_VIEW_STORES                  32772
#define ID_STORE_INFO                   32773
#define IDC_SUB_RETAINAGE               32774
#define IDC_SUB_DATA                    32775
#define ID_VIEW_SUBCONTRACTORS          32776
#define ID_VIEW_CUSTOMER_PO             32778
#define ID_RELEASE                      32779
#define ID_INVOICING                    32780
#define ID_BILLING_RECEIVECHECK         32781
#define ID_FIND_BY_PO                   32782
#define ID_FIND_BY_ORDER_NUMBER         32783
#define ID_FIND_BY_CUSTOMER_NUMBER      32784
#define ID_BILLING_CHARGEBACKS          32785
#define IDC_PULL_LIST                   32786
#define ID_OVERDUE_INVOICES             32787
#define ID_PAYROLL                      32788
#define ID_REPORTS_PENDING              32790
#define ID_NOT_BILLED                   32791
#define ID_INVENTORY                    32792
#define ID_FIND_BY_SPECIAL_ORDER        32793
#define ID_CRIMINAL_CHECKS              32794
#define ID_CRIMINAL_CHECKS_DATE         32795
#define ID_CRIMINAL_CHECK_DATE          32797
#define ID_REPORTS_SUBCONTRACTORS_CRIMINALCHECKS_BYNAME 32798
#define ID_REPORTS_SUBCONTRACTORS_WORKMANSCOMP_BYDATE 32799
#define ID_WORKMANSCOMP_BYDATE          32800
#define ID_REPORTS_SUBCONTRACTORS_WORKMANSCOMP_BYNAME 32801
#define ID_WORKMANSCOMP_BYNAME          32802
#define ID_CRIMINAL_CHECK_NAME          32803
#define ID_REPORTS_BILLING              32804
#define ID_MATERIALS_CHANGESTATUS       32805
#define ID_REPORTS_MATERIALS_NOTRECEIVEDYET 32807
#define ID_BILLING_PAYROLL_PROCESSWORKORDERS 32808
#define ID_BILLING_PAYROLL_PROCESSBILLS 32809
#define ID_BILLING_PAYROLL_GENERATECHECKS 32810
#define ID_VIEW_JOBASSIGNMENT           32811
#define ID_OPEN_INVOICE                 32813
#define ID_REPORTS_STATUS               32814
#define ID_WARRANTY_OPEN                32815
#define ID_WARRANTY_SCHED               32816
#define ID_MATERIAL_RA                  32817
#define ID_MATERIALS_NOTRECEIVEDYET     32818
#define ID_EDIT_PO_NUM                  32819
#define ID_EDIT_CLEARREADONLY           32820
#define DM_VIEW_CUSTOMER_PO             32822
#define ID_REPORTS_STATUS_SINGLE        32823
#define ID_REPORTS_STATUSREPORT_SUMMARY_SINGLESTORE 32825
#define ID_REPORTS_STATUS_SINGLE_SUMMARY 32826
#define ID_REPORTS_STATUS_SUMMARY       32827
#define ID_SUB_PHONELIST                32828
#define ID_EDIT_EDITPONUMBER            32829
#define ID_BACKGROUNDCHECKS_ALPHABYLASTNAME 32830
#define ID_REPORTS_JOBS                 32831
#define ID_JOBS_ASSIGNMENTS             32832
#define ID_REPORTS_INVOICING            32834
#define ID_REPORTS_FINANCIAL            32835
#define ID_JOBS_STATUS                  32836
#define ID_JOBS_STATUS32837             32837
#define ID_FIND_BYPHONENUMBER           32838
#define ID_FIND_BY_HOME_PHONENUMBER     32841
#define ID_FIND_BY_WORK_PHONENUMBER     32842
#define ID_PAYROLL_MESSAGES             32843
#define ID_SUB_HELPERS                  32844
#define ID_FINANCIAL_MATERIALPRICING    32845
#define ID_MAINTENANCE_SPNDISCREPANCIES 32846
#define ID_MAINTENANCE_IMPORTEDPOSTATUS 32848
#define ID_FIND_BYSEARCHINGNOTES        32849
#define ID_REPORTS_FINANCIAL_MATERIAL_PRICING 32850
#define IDC_SHOW_DELETED                32851
#define ID_VIEW_SHOWUNITCOST            32852
#define ID_VIEW_SHOWINACTIVEMATERIALS   32853
#define ID_VIEW_SHOWCFIPRICE            32854
#define ID_VIEW_SHOWDELETED             32855
#define ID_VIEW_USERALERTS              32856
#define ID_LIABILITY_BY_DATE            32857
#define ID_WORKMANS_COMP_BY_DATE        32858
#define ID_HELP_REPORTISSUE             32859
#define ID_VIEW_ACTIVEPOS               32876
#define ID_VIEW_ACTIVITYLIST            32878
#define ID_MATERIALS_DAMAGED            32880
#define ID_FILE_SETEMAILPASSWORD        32881
#define ID_MAINTENANCE_UNIT             32884
#define ID_MAINTENANCE_UNITTESTS        32885
#define ID_VIEW_JOBASSIGN               32886
#define ID_MATERIALS_FICONSUPTION       32887
#define ID_JOBS_SCHEDULE                32888
#define ID_JOBS_BILLINGCOVER            32889

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        245
#define _APS_NEXT_COMMAND_VALUE         32890
#define _APS_NEXT_CONTROL_VALUE         1386
#define _APS_NEXT_SYMED_VALUE           123
#endif
#endif
